import plato.*;

brutus = getScheduler('lsf');
for iJob = 1:4
    [status, result] = brutus.submit([ ...
        'disp(''Hello there!'');\n' ...
        'disp(''This is job {0}'');\n' ...
        ], ...
        {iJob} ...
    );
    disp(result)
end
    
