#! /bin/sh
#
# iBRAIN.sh/searchforpreclusterfile searchpath defaultfile
#
# usage:
# searchforpreclusterfile.s SEARCHPATH DEFAULTPRECLUSTERFILE PRECLUSTERBACKUPPATH

SEARCHPATH="$1"
DEFAULTPRECLUSTERSETTINGS="$2"
PRECLUSTERBACKUPPATH="$3"

### SET PRECLUSTER SETTINGS FILE TO DEFAULT
PRECLUSTERSETTINGS="$DEFAULTPRECLUSTERSETTINGS"

if [ -d "$SEARCHPATH" ]; then

### LOOKING FOR PRECLUSTER SETTINGS FILE IN GIVEN PATH
for FOUNDSETTINGSFILE in `find $SEARCHPATH -maxdepth 1 -type f -iname 'PreCluster*.mat'`
do
PRECLUSTERSETTINGS="$FOUNDSETTINGSFILE"
done

### IF THIS FILE IS NOT THE DEFAULT, AND HAS NOT BEEN BACKED-UP, DO SO
if [ ! "$PRECLUSTERSETTINGS" = "$DEFAULTPRECLUSTERSETTINGS" ] && [ ! -e "$PRECLUSTERBACKUPPATH/$(basename $FOUNDSETTINGSFILE)" ] && [ -e $PRECLUSTERBACKUPPATH ] && [ "$PRECLUSTERBACKUPPATH" ] ; then
cp "$PRECLUSTERSETTINGS" "$PRECLUSTERBACKUPPATH/$(basename $FOUNDSETTINGSFILE)"
fi

fi # check if input path exists

### RETURN RESULTANT PRECLUSTER FILE
echo ${PRECLUSTERSETTINGS}
