#! /bin/sh
if [ ! -d $IBRAIN_ROOT ]; then
    echo "Error, missing ROOT folder definition.." >/dev/stderr
    exit
fi

export IBRAIN_BIN_PATH=$IBRAIN_ROOT/bin
export IBRAIN_ETC_PATH=$IBRAIN_ROOT/etc
export IBRAIN_VAR_PATH=$IBRAIN_ROOT/var
export IBRAIN_LOG_PATH=$IBRAIN_VAR_PATH/log
export IBRAIN_DATABASE_PATH=$IBRAIN_VAR_PATH/database

export IBRAIN_USER=$(whoami)
export IBRAIN_ADMIN_EMAIL=yauhen.yakimovich@uzh.ch

export CELLPROFILER2_PATH=~/CellProfiler2
export PYTHON_CMD="/usr/bin/env python2.7"
export MATLAB_CMD="/usr/bin/env matlab -singleCompThread -nodisplay -nojvm"

# Alternatively pick from {'shellcmd', 'lsf'}
export SCHEDULING_ENGINE="shellcmd"

# Applied to map relative path to full path on a cluster. Example:
#export IBRAIN_SED_SHARES='s|/share-\([0-9]\)|/BIOL/sonas/biol_uzh_pelkmans_s\1|g'
# Leave it empty if you don't need it.
export IBRAIN_SED_SHARES=''

export IBRAIN_VERSION="$(cat $IBRAIN_ROOT/VERSION)"
IBRAIN_GIT_FOLDER=$IBRAIN_ROOT/../code/iBRAIN
if [ -d $IBRAIN_GIT_FOLDER ]; then
	IBRAIN_VERSION_IBRAIN_HASHTAG="<iBRAIN_git_hashtag>$(cd $IBRAIN_GIT_FOLDER && git rev-parse HEAD)</iBRAIN_git_hashtag>"
	if [ -d $IBRAIN_GIT_FOLDER/../dep ]; then
		IBRAIN_VERSION_DEP_HASHTAG="<dep_git_hashtag>$(cd $IBRAIN_GIT_FOLDER/../dep && git rev-parse HEAD)</dep_git_hashtag>"
	fi
    if [ -d $IBRAIN_GIT_FOLDER/../CellProfiler2 ]; then
        IBRAIN_VERSION_CP2_HASHTAG="<cp2_git_hashtag>$(cd $IBRAIN_GIT_FOLDER/../CellProfiler2 && git rev-parse HEAD)</cp2_git_hashtag>"
    fi
fi
# IS included in the meta information of iBRAIN
export IBRAIN_VERSION_INFO="<version>$IBRAIN_VERSION</version>${IBRAIN_VERSION_IBRAIN_HASHTAG}${IBRAIN_VERSION_DEP_HASHTAG}${IBRAIN_VERSION_CP2_HASHTAG}"


export PATH=$PATH:$IBRAIN_BIN_PATH

