WGET=/usr/bin/wget
TIFF_URL=http://www.infectome.ethz.ch/data/iBRAIN/plate/TIFF/


all: getimages

clean: 
	rm *.png

getimages: B06f00d0.png B06f00d1.png B06f01d0.png B06f01d1.png B06f02d0.png\
	B06f02d1.png B06f03d0.png B06f03d1.png B06f04d0.png B06f04d1.png B06f05d0.png\
	B06f05d1.png B06f06d0.png B06f06d1.png B06f07d0.png B06f07d1.png B06f08d0.png\
	B06f08d1.png

B06f00d0.png:
		${WGET} ${TIFF_URL}$@

B06f00d1.png:
		${WGET} ${TIFF_URL}$@

B06f01d0.png:
		${WGET} ${TIFF_URL}$@
		
B06f01d1.png:
		${WGET} ${TIFF_URL}$@

B06f02d0.png:
		${WGET} ${TIFF_URL}$@

B06f02d1.png:
		${WGET} ${TIFF_URL}$@

B06f03d0.png:
		${WGET} ${TIFF_URL}$@

B06f03d1.png:
		${WGET} ${TIFF_URL}$@

B06f04d0.png:
		${WGET} ${TIFF_URL}$@

B06f04d1.png:
		${WGET} ${TIFF_URL}$@

B06f05d0.png:
		${WGET} ${TIFF_URL}$@

B06f05d1.png:
		${WGET} ${TIFF_URL}$@

B06f06d0.png:
		${WGET} ${TIFF_URL}$@

B06f06d1.png:
		${WGET} ${TIFF_URL}$@

B06f07d0.png:
		${WGET} ${TIFF_URL}$@

B06f07d1.png:
		${WGET} ${TIFF_URL}$@

B06f08d0.png:
		${WGET} ${TIFF_URL}$@

B06f08d1.png:
		${WGET} ${TIFF_URL}$@

