#! /bin/sh
if [ ! -d $IBRAIN_ROOT ]; then
    echo "Error, missing ROOT folder definition.." >/dev/stderr
    exit
fi

export IBRAIN_BIN_PATH=$IBRAIN_ROOT/bin
export IBRAIN_ETC_PATH=$IBRAIN_ROOT/etc
export IBRAIN_VAR_PATH=$IBRAIN_ROOT/var
export IBRAIN_LOG_PATH=$IBRAIN_VAR_PATH/log
export IBRAIN_DATABASE_PATH=$IBRAIN_VAR_PATH/database

export IBRAIN_USER=$(whoami)
export IBRAIN_ADMIN_EMAIL=yauhen.yakimovich@uzh.ch

export CELLPROFILER2_PATH=~/CellProfiler2
export PYTHON_CMD="/usr/bin/env python2.7"
export MATLAB_CMD="/usr/bin/env matlab -singleCompThread -nodisplay -nojvm"

# Alternatively pick from {'shellcmd', 'lsf'}
export SCHEDULING_ENGINE="shellcmd"

# Applied to map relative path to full path on a cluster. Example:
#export IBRAIN_SED_SHARES='s|/share-\([0-9]\)|/BIOL/sonas/biol_uzh_pelkmans_s\1|g'
# Leave it empty if you don't need it.
export IBRAIN_SED_SHARES=''


export PATH=$PATH:$IBRAIN_BIN_PATH

