%This script prepeares is used for preparartion of vesicle features. As of
%Jan 2011 the Ibrain pipelines in use do not compute some of the vesicles
%features such as location or clustering.
%The script read the basic vesicle information available and uses it
%together with cell information to derive all other informations

%Path to plate to create vesicle features for

%Config files which include vesicle features

%Filename to store single cell vesicle features
%The following vesicle features are stored here
% -v5:Rel. Distance to nucleus Number between 0 and 1 obtained by distance)(GFP
% Pixel-Nucleus Position)/Cell size
% -v6:Number of neighbours within 2.75 um
% -v7: Number of neighbours within 3.8 um
% -v8: Radious containing 40 % of all vesicles
%-v9: Radius containing 60 % of all vesicles
function [t]=computeTexture_part1(assay_index)

texture_file='Measurements_Cell_Texture';
%Constant which defines the number of pixle per um
um_pixel=100;

%Filename to store vesicle features of a total cell
%-c1: Number of vesicles per cell area
%-c2: Clusering of spatial point pattern Ripleys K
%-c3: Regularity of spatial point pattern Ripley K

          plate_paths={        
              '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090309_A431-Chtx-GM130/090309_A431-Chtx-GM130-CP392-1af/BATCH', ...
                        '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090309_A431-Chtx-GM130/090309_A431-Chtx-GM130-CP393-1af/BATCH', ...
                        '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090309_A431-Chtx-GM130/090309_A431-Chtx-GM130-CP394-1af/BATCH', ...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090309_A431-Chtx-GM130/090309_A431-Chtx-GM130-CP395-1af/BATCH', ...
 '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090203_Mz_Tf_EEA1_harlink_03_1ad/090203_Mz_Tf_EEA1_CP392-1ad/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090203_Mz_Tf_EEA1_harlink_03_1ad/090203_Mz_Tf_EEA1_CP393-1ad/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090203_Mz_Tf_EEA1_harlink_03_1ad/090203_Mz_Tf_EEA1_CP394-1ad/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090203_Mz_Tf_EEA1_harlink_03_1ad/090203_Mz_Tf_EEA1_CP395-1ad/BATCH', ...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090217_A431_Tf_EEA1/090217_A431_Tf_EEA1_CP392-1ae/BATCH',  ...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090217_A431_Tf_EEA1/090217_A431_Tf_EEA1_CP393-1ae/BATCH', ...
                             '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090217_A431_Tf_EEA1/090217_A431_Tf_EEA1_CP394-1ae/BATCH' , ...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090217_A431_Tf_EEA1/090217_A431_Tf_EEA1_CP395-1ae/BATCH', ...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090928_A431_Chtx_Lamp1/090309_A431_Chtx_Lamp1_CP392-1ba/BATCH', ...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090928_A431_Chtx_Lamp1/090309_A431_Chtx_Lamp1_CP393-1ba/BATCH', ...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090928_A431_Chtx_Lamp1/090309_A431_Chtx_Lamp1_CP394-1ba/BATCH', ...
                          '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090928_A431_Chtx_Lamp1/090309_A431_Chtx_Lamp1_CP395-1ba/BATCH', ...
                           '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090403_A431_Dextran_GM1/090403_A431_Dextran_GM1-CP392-1ag/BATCH', ...
                        '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090403_A431_Dextran_GM1/090403_A431_Dextran_GM1-CP393-1ag/BATCH', ...
                        '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090403_A431_Dextran_GM1/090403_A431_Dextran_GM1-CP394-1ag/BATCH', ...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/090403_A431_Dextran_GM1/090403_A431_Dextran_GM1-CP395-1ag/BATCH', ...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/091127_A431_Chtx_Golgi_AcidWash/091127_A431_Chtx_Golgi_AcidWash_CP392-1bf/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/091127_A431_Chtx_Golgi_AcidWash/091127_A431_Chtx_Golgi_AcidWash_CP393-1bf/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/091127_A431_Chtx_Golgi_AcidWash/091127_A431_Chtx_Golgi_AcidWash_CP394-1bf/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/091127_A431_Chtx_Golgi_AcidWash/091127_A431_Chtx_Golgi_AcidWash_CP395-1bf/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100215_A431_Actin_LDL/100215_A431_Actin_LDL_CP392-1bi/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100215_A431_Actin_LDL/100215_A431_Actin_LDL_CP393-1bi/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100215_A431_Actin_LDL/100215_A431_Actin_LDL_CP394-1bi/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100215_A431_Actin_LDL/100215_A431_Actin_LDL_CP395-1bi/BATCH',...
                          '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100224_A431_EGF_Cav1/100224_A431_EGF_Cav1_CP392-1ba/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100224_A431_EGF_Cav1/100224_A431_EGF_Cav1_CP393-1ba/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100224_A431_EGF_Cav1/100224_A431_EGF_Cav1_CP394-1ba/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100224_A431_EGF_Cav1/100224_A431_EGF_Cav1_CP395-1ba/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/091113_A431_GPIGFP/091113_A431GPIGFP_CP392-1be/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/091113_A431_GPIGFP/091113_A431GPIGFP_CP393-1be/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/091113_A431_GPIGFP/091113_A431GPIGFP_CP394-1be/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/091113_A431_GPIGFP/091113_A431GPIGFP_CP395-1be/BATCH',...
                          '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100402_A431_Macropinocytosis/100402_A431_Macropinocytosis_CP392-1bd/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100402_A431_Macropinocytosis/100402_A431_Macropinocytosis_CP393-1bd/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100402_A431_Macropinocytosis/100402_A431_Macropinocytosis_CP394-1bd/BATCH',...
                         '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Prisca/100402_A431_Macropinocytosis/100402_A431_Macropinocytosis_CP395-1bd/BATCH'};
cell_file='Measurements_Cell_Vesicle_Features-v2';
vesicle_names={
 'ChtxVes',...    
 'TfVesicles',...
      'TfVesicles',...
        'ChtVesicles',...
    'DextranVesicles',...
    'ChtVesicles',...
    'LDLVesicles',...
    'EGFVesicles',...
    'GFPVesicles',...
   'MacroVesicles',...
   };


           config_paths={

                 '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090309_A431-Chtx-GM130.txt',...
                 '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090309_A431-Chtx-GM130.txt',...
                 '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090309_A431-Chtx-GM130.txt',...
                 '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090309_A431-Chtx-GM130.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090203_Mz_Tf_EEA1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090203_Mz_Tf_EEA1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090203_Mz_Tf_EEA1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090203_Mz_Tf_EEA1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090217_A431_Tf_EEA1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090217_A431_Tf_EEA1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090217_A431_Tf_EEA1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090217_A431_Tf_EEA1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090928_A431_Chtx_Lamp1_chtxchannel.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090928_A431_Chtx_Lamp1_chtxchannel.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090928_A431_Chtx_Lamp1_chtxchannel.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090928_A431_Chtx_Lamp1_chtxchannel.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090403_A431_Dextran_GM1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090403_A431_Dextran_GM1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090403_A431_Dextran_GM1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-090403_A431_Dextran_GM1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-091127_A431_Chtx_Golgi_AcidWash.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-091127_A431_Chtx_Golgi_AcidWash.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-091127_A431_Chtx_Golgi_AcidWash.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-091127_A431_Chtx_Golgi_AcidWash.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100215_A431_Actin_LDL.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100215_A431_Actin_LDL.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100215_A431_Actin_LDL.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100215_A431_Actin_LDL.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100224_A431_EGF_Cav1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100224_A431_EGF_Cav1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100224_A431_EGF_Cav1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100224_A431_EGF_Cav1.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-091113_A431_GPIGFP.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-091113_A431_GPIGFP.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-091113_A431_GPIGFP.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-091113_A431_GPIGFP.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100402_A431_Macropinocytosis.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100402_A431_Macropinocytosis.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100402_A431_Macropinocytosis.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100402_A431_Macropinocytosis.txt',...
                     '/BIOL/imsb/fs3/bio3/bio3/Data/Users/Yanic/measurement_output/ProbModel_Settings_QuantPlot-100402_A431_Macropinocytosis.txt'
                     
                 };

             
          
             channels=[
            2,2,2,3,3,3,3,2,3,3 
             
             ];
         channel_names={'RescaledGreen','RescaledGreen','RescaledGreen','RescaledRed','RescaledRed','RescaledRed','RescaledRed','RescaledGreen','RescaledRed','RescaledRed'};

         status=fopen(npc(strcat('/cluster/home/biol/lprisca/tex/tex',sprintf('%d',ceil(assay_index/4)),'/','Measurements_Texture',sprintf('%d',assay_index))));
         if(status==-1)
%Loop over plates
for(plate=assay_index:assay_index)
    %Load basic data
    
                       basic_files=dir(npc(strcat(plate_paths{plate},'/*BASICDATA*')));
        if(size(basic_files,1)>1)
            sprintf(strcat('More than 1 basic data file:',basic_file{1}.name,' is used'))
        end;
        basic_path=basic_files.name;
        load(npc(strcat(plate_paths{plate},'/',basic_path)));
       
        %Load parents,locations and intensities
        
        %Special case TF plates
%         if((plate<13)&&(plate>4))
%                    load(npc(strcat(plate_paths{plate},'/','Measurements_','TfPixel','_Parent.mat')));
       %     parents1=eval((strcat('handles.Measurements.',vesicle_names{ceil(plate/4)},'.Parent')));
  
         %  load(strcat(plate_paths{plate},'/','Measurements_',vesicle_names{plate},'_Intensity_RescaledRed.mat'));
        %intensities1=eval(strcat('handles.Measurements.',vesicle_names{plate},'.Intensity_RescaledRed'));

    PlateDataHandles = struct();
    PlateDataHandles = LoadMeasurements(PlateDataHandles,npc([plate_paths{plate},'/','Measurements_Image_FileNames.mat']));

    %Allocate mariz for v8 features

    %Path to TIFF directory of current plate
    image_path=strrep(plate_paths{plate},'/BATCH','/TIFF');
%'Z:\Data\Users\Prisca\090203_Mz_Tf_EEA1_harlink_03_1ad\090203_Mz_Tf_EEA1_CP392-1ad\TIFF\';
%Path to Segmentation directory of current plate
segmentation_path=strrep(plate_paths{plate},'/BATCH','/SEGMENTATION');
% load(npc(strcat(plate_paths{plate},'/','Batch_data.mat')));
% ident_column=handles.Settings.VariableValues;
% ident_column1=ident_column(:,2);
% %Get index of rescaled green or rescaledred
% index_rescaled=find(strcmp(ident_column1,channel_names{(ceil(assay_index/4))}));
% LowestPixelOrig=str2num(ident_column{index_rescaled,4});
% HighestPixelOrig=str2num(ident_column{index_rescaled,5});
% LowestPixelRescale=str2num(ident_column{index_rescaled,6});
% HighestPixelRescale=str2num(ident_column{index_rescaled,7});
LowestPixelOrig=0.0021;
HighestPixelOrig=1;
LowestPixelRescale=0;
HighestPixelRescale=1;

 texture_all=cell(length(PlateDataHandles.Measurements.Image.FileNames),1);
    for(image=1:length(PlateDataHandles.Measurements.Image.FileNames))
        %Copied from the cprescale function
        %Load proper channel
        string_r=npc([image_path,'\',PlateDataHandles.Measurements.Image.FileNames{image}{channels(ceil(assay_index/4))}]);
        channel_image1 = imread(string_r);
        
        channel_image=double(channel_image1)/double(max(max(channel_image1)));  
        %%% Rescales the Image.
    InputImageMod = channel_image;
    %Any pixel in the original image lower than the user-input lowest bound is
    %pinned to the lowest value.
    InputImageMod(InputImageMod < LowestPixelOrig) = LowestPixelOrig;
    %Any pixel in the original image higher than the user-input highest bound is
    %pinned to the lowest value.
    InputImageMod(InputImageMod > HighestPixelOrig) = HighestPixelOrig;
    %Scales and shifts the original image to produce the rescaled image
    scaleFactor = (HighestPixelRescale - LowestPixelRescale)  / (HighestPixelOrig - LowestPixelOrig);
    shiftFactor = LowestPixelRescale - LowestPixelOrig;
    OutputImage = InputImageMod + shiftFactor;
    channel_image = OutputImage * scaleFactor;
    %End of copy
    
 string_r=npc([segmentation_path,'\',PlateDataHandles.Measurements.Image.FileNames{image}{1}(1:end-4),'_SegmentedCells.png']);
       
            current_segmentation = imread(string_r);
        

  
        if(mod(image,100)==0)
            image
        end;

    %Loop over all cells
    %Allocate array for current image
    num_cells=max(max(current_segmentation));
    new_array=NaN(num_cells,22);

    %Loop onlyover all cells of a given segmentation
    for(cell_index1=1:num_cells)
          %Get list of pixles for current cell
              
                
                [ix,iy]=find(current_segmentation==(cell_index1));
                if(isempty(ix))
                    %Non used nucleus
                    continue;
                end;
                coords=[ix,iy];
                minx=min(ix);
                maxx=max(ix);
                miny=min(iy);
                maxy=max(iy);
         
               
                %Create coordinates of possible neighbours
                offset=[0 1; -1 1; -1 0; -1 -1];
                potential_neighbours=[[coords+offset(1,1),coords+offset(1,2)];[coords+offset(2,1),coords+offset(2,2)];[coords+offset(3,1),coords+offset(3,2)];[coords+offset(4,1),coords+offset(4,2)]];
                %Remove pairs having one coordinate not in pixels_x or
                %pixels_y
                rows=find(potential_neighbours(:,1)>=minx & potential_neighbours(:,2) >=miny & potential_neighbours(:,2) <=maxy & potential_neighbours(:,1) <=maxx);
              %Extract pixels values of pairs of pixels
              I=ix + (iy - 1)*size(channel_image,1);
                GL=[min(min(channel_image(I))),max(max(channel_image(I)))];
              I=[I;I;I;I];
              In=potential_neighbours(:,1) + (potential_neighbours(:,2) - 1)*size(channel_image,1);
              NL=8;
            
                slope = (NL-1) / (GL(2) - GL(1));
  intercept = 1 - (slope*(GL(1)));
  SI = round(imlincomb(slope,channel_image(I(rows)),intercept,'double'));
   SI1 = round(imlincomb(slope,channel_image(In(rows)),intercept,'double'));
   SI(SI > NL) = NL;
SI(SI < 1) = 1;
SI1(SI1 > NL) = NL;
SI1(SI1 < 1) = 1;
              all_pairs=[SI,SI1];
              A=accumarray(all_pairs,1,[8 8]);
        
                new_array((cell_index1),:)=struct2array(GLCM_Features4(A,0));
        

    end;
texture_all{image}=new_array;
        end;
    end;
           

    %Write new vesicle feature measurement file
    texture_cell={'1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22'};
    mkdir(strcat('/cluster/home/biol/lprisca/tex/tex',sprintf('%d',ceil(assay_index/4))));
    handles=struct('Measurements',struct('Custom',struct('TextureFeatures',{texture_cell},'Texture',{texture_all})));
     save((strcat('/cluster/home/biol/lprisca/tex/tex',sprintf('%d',ceil(assay_index/4)),'/','Measurements_Texture',sprintf('%d',plate))),'handles');
      

         end;
         fclose(status);
end